
interface ISchemaDefs {
  [key: string]: string;
		CreateCart_items: string;
	ReadCart_itemsFilters: string;
	ReadCart_itemsOrders: string;
	ReadCart_itemsQuery: string;
	ReadCart_itemsRelations: string;
	ReadOneCart_itemsQuery: string;
	UpdateCart_items: string;
	CreateOrders: string;
	ReadOneOrdersQuery: string;
	ReadOrdersFilters: string;
	ReadOrdersOrders: string;
	ReadOrdersQuery: string;
	ReadOrdersRelations: string;
	UpdateOrders: string;
	CreateOrder_items: string;
	ReadOneOrder_itemsQuery: string;
	ReadOrder_itemsFilters: string;
	ReadOrder_itemsOrders: string;
	ReadOrder_itemsQuery: string;
	ReadOrder_itemsRelations: string;
	UpdateOrder_items: string;
	CreateProducts: string;
	ReadOneProductsQuery: string;
	ReadProductsFilters: string;
	ReadProductsOrders: string;
	ReadProductsQuery: string;
	ReadProductsRelations: string;
	UpdateProducts: string;
	CreateReviews: string;
	ReadOneReviewsQuery: string;
	ReadReviewsFilters: string;
	ReadReviewsOrders: string;
	ReadReviewsQuery: string;
	ReadReviewsRelations: string;
	UpdateReviews: string;
	CreateUsers: string;
	ReadOneUsersQuery: string;
	ReadUsersFilters: string;
	ReadUsersOrders: string;
	ReadUsersQuery: string;
	ReadUsersRelations: string;
	UpdateUsers: string;
}

export const SchemaDefs: ISchemaDefs = {
			CreateCart_items: '#/components/schemas/CreateCart_items',
	ReadCart_itemsFilters: '#/components/schemas/ReadCart_itemsFilters',
	ReadCart_itemsOrders: '#/components/schemas/ReadCart_itemsOrders',
	ReadCart_itemsQuery: '#/components/schemas/ReadCart_itemsQuery',
	ReadCart_itemsRelations: '#/components/schemas/ReadCart_itemsRelations',
	ReadOneCart_itemsQuery: '#/components/schemas/ReadOneCart_itemsQuery',
	UpdateCart_items: '#/components/schemas/UpdateCart_items',
	CreateOrders: '#/components/schemas/CreateOrders',
	ReadOneOrdersQuery: '#/components/schemas/ReadOneOrdersQuery',
	ReadOrdersFilters: '#/components/schemas/ReadOrdersFilters',
	ReadOrdersOrders: '#/components/schemas/ReadOrdersOrders',
	ReadOrdersQuery: '#/components/schemas/ReadOrdersQuery',
	ReadOrdersRelations: '#/components/schemas/ReadOrdersRelations',
	UpdateOrders: '#/components/schemas/UpdateOrders',
	CreateOrder_items: '#/components/schemas/CreateOrder_items',
	ReadOneOrder_itemsQuery: '#/components/schemas/ReadOneOrder_itemsQuery',
	ReadOrder_itemsFilters: '#/components/schemas/ReadOrder_itemsFilters',
	ReadOrder_itemsOrders: '#/components/schemas/ReadOrder_itemsOrders',
	ReadOrder_itemsQuery: '#/components/schemas/ReadOrder_itemsQuery',
	ReadOrder_itemsRelations: '#/components/schemas/ReadOrder_itemsRelations',
	UpdateOrder_items: '#/components/schemas/UpdateOrder_items',
	CreateProducts: '#/components/schemas/CreateProducts',
	ReadOneProductsQuery: '#/components/schemas/ReadOneProductsQuery',
	ReadProductsFilters: '#/components/schemas/ReadProductsFilters',
	ReadProductsOrders: '#/components/schemas/ReadProductsOrders',
	ReadProductsQuery: '#/components/schemas/ReadProductsQuery',
	ReadProductsRelations: '#/components/schemas/ReadProductsRelations',
	UpdateProducts: '#/components/schemas/UpdateProducts',
	CreateReviews: '#/components/schemas/CreateReviews',
	ReadOneReviewsQuery: '#/components/schemas/ReadOneReviewsQuery',
	ReadReviewsFilters: '#/components/schemas/ReadReviewsFilters',
	ReadReviewsOrders: '#/components/schemas/ReadReviewsOrders',
	ReadReviewsQuery: '#/components/schemas/ReadReviewsQuery',
	ReadReviewsRelations: '#/components/schemas/ReadReviewsRelations',
	UpdateReviews: '#/components/schemas/UpdateReviews',
	CreateUsers: '#/components/schemas/CreateUsers',
	ReadOneUsersQuery: '#/components/schemas/ReadOneUsersQuery',
	ReadUsersFilters: '#/components/schemas/ReadUsersFilters',
	ReadUsersOrders: '#/components/schemas/ReadUsersOrders',
	ReadUsersQuery: '#/components/schemas/ReadUsersQuery',
	ReadUsersRelations: '#/components/schemas/ReadUsersRelations',
	UpdateUsers: '#/components/schemas/UpdateUsers',
}