services:
  postgres-db:
    container_name: deira-postgres-db
    image: postgres:16
    restart: unless-stopped
    env_file: '.env'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_DOCKER_PORT}
    volumes:
      - deira-db-vol:/var/lib/postgresql/data
    networks:
      - deira-net
  api:
    container_name: api
    depends_on:
      - postgres-db
    build: .
    restart: unless-stopped
    env_file: '.env'
    ports:
      - $PORT:$DOCKER_PORT
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - deira-net

networks:
  deira-net:
volumes:
  deira-db-vol:
