import * as v from 'valibot';
import { NotificationType } from '<<pathToOriginal>>';

export const CreateNotificationSchema = v.pipe(v.object({customContent: v.string(),
isRead: v.boolean(),
user: v.nullish(v.union([v.number(), v.object({email: v.nullish(v.string()),
phone: v.nullish(v.string()),
password: v.nullish(v.string()),
firebaseId: v.nullish(v.string()),
emailVerified: v.nullish(v.boolean()),
isGoogleSignin: v.nullish(v.boolean()),
isAppleSignin: v.nullish(v.boolean()),
isFollowing: v.nullish(v.boolean()),
isBlockedBy: v.nullish(v.boolean()),
followersCount: v.nullish(v.number())})])),
collaboration: v.nullish(v.union([v.number(), v.object({brandId: v.nullish(v.number()),
shopperId: v.nullish(v.number())})])),
comment: v.nullish(v.union([v.number(), v.object({content: v.string(),
level: v.number(),
userId: v.number(),
replyToId: v.undefinedable(v.number()),
postId: v.undefinedable(v.number()),
repliesDepth: v.number()})])),
promotion: v.nullish(v.union([v.number(), v.object({title: v.string(),
discountPercentage: v.number(),
minPurchaseAmount: v.nullish(v.number()),
start: v.pipe(v.string('Invalid type: Expected ISO timestamp string'), v.isoTimestamp()),
end: v.pipe(v.string('Invalid type: Expected ISO timestamp string'), v.isoTimestamp()),
isDeleted: v.boolean(),
seasonalPromotionId: v.nullish(v.number()),
brandId: v.number()})])),
product: v.nullish(v.union([v.number(), v.object({isArchived: v.boolean(),
title: v.nullish(v.string()),
description: v.nullish(v.string()),
basePrice: v.nullish(v.number()),
sku: v.nullish(v.string()),
currency: v.nullish(v.string()),
stock: v.number(),
lastStockUpdate: v.nullish(v.pipe(v.string('Invalid type: Expected ISO timestamp string'), v.isoTimestamp())),
isOutOfStock: v.boolean(),
isFeatured: v.boolean(),
deliveryEstimationInDays: v.number(),
brandId: v.nullish(v.number()),
categoryId: v.nullish(v.number()),
subCategoryId: v.nullish(v.number()),
averageRating: v.number(),
isSaved: v.boolean()})])),
userId: v.number(),
collaborationId: v.number(),
commentId: v.number(),
promotionId: v.number(),
productId: v.number()}),v.metadata({user: 'UserEntity',
collaboration: 'CollaborationEntity',
comment: 'CommentEntity',
promotion: 'PromotionEntity',
product: 'ProductEntity'}))

export type TCreateNotificationSchema = v.InferInput<typeof CreateNotificationSchema>
