
interface ISchemaDefs {
  [key: string]: string;
		CreateAffiliationLinkTracking: string;
	CreateAffiliationLink: string;
	ReadAffiliationLinkFilters: string;
	ReadAffiliationLinkOrders: string;
	ReadAffiliationLinkQuery: string;
	ReadAffiliationLinkRelations: string;
	ReadAffiliationLinkTrackingFilters: string;
	ReadAffiliationLinkTrackingOrders: string;
	ReadAffiliationLinkTrackingQuery: string;
	ReadAffiliationLinkTrackingRelations: string;
	UpdateAffiliationLinkTracking: string;
	UpdateAffiliationLink: string;
	CreateCartItems: string;
	CreateCart: string;
	ReadCartFilters: string;
	ReadCartItemsFilters: string;
	ReadCartItemsOrders: string;
	ReadCartItemsQuery: string;
	ReadCartItemsRelations: string;
	ReadCartOrders: string;
	ReadCartQuery: string;
	ReadCartRelations: string;
	UpdateCartItems: string;
	UpdateCart: string;
	CreateCategory: string;
	ReadCategoryFilters: string;
	ReadCategoryOrders: string;
	ReadCategoryQuery: string;
	ReadCategoryRelations: string;
	UpdateCategory: string;
	CreateCollaboration: string;
	ReadCollaborationFilters: string;
	ReadCollaborationOrders: string;
	ReadCollaborationQuery: string;
	ReadCollaborationRelations: string;
	UpdateCollaboration: string;
	CreateCollection: string;
	ReadCollectionFilters: string;
	ReadCollectionOrders: string;
	ReadCollectionQuery: string;
	ReadCollectionRelations: string;
	UpdateCollection: string;
	CreateComment: string;
	ReadCommentFilters: string;
	ReadCommentOrders: string;
	ReadCommentQuery: string;
	ReadCommentRelations: string;
	UpdateComment: string;
	CreateConversation: string;
	ReadConversationFilters: string;
	ReadConversationOrders: string;
	ReadConversationQuery: string;
	ReadConversationRelations: string;
	UpdateConversation: string;
	CreateCountry: string;
	ReadCountryFilters: string;
	ReadCountryOrders: string;
	ReadCountryQuery: string;
	ReadCountryRelations: string;
	UpdateCountry: string;
	CreateMedia: string;
	ReadMediaFilters: string;
	ReadMediaOrders: string;
	ReadMediaQuery: string;
	ReadMediaRelations: string;
	UpdateMedia: string;
	CreateMessage: string;
	ReadMessageFilters: string;
	ReadMessageOrders: string;
	ReadMessageQuery: string;
	ReadMessageRelations: string;
	UpdateMessage: string;
	CreateNotification: string;
	ReadNotificationFilters: string;
	ReadNotificationOrders: string;
	ReadNotificationQuery: string;
	ReadNotificationRelations: string;
	UpdateNotification: string;
	CreateBrandOrder: string;
	CreateOrderItem: string;
	CreateOrder: string;
	ReadBrandOrderFilters: string;
	ReadBrandOrderOrders: string;
	ReadBrandOrderQuery: string;
	ReadBrandOrderRelations: string;
	ReadOrderFilters: string;
	ReadOrderItemFilters: string;
	ReadOrderItemOrders: string;
	ReadOrderItemQuery: string;
	ReadOrderItemRelations: string;
	ReadOrderOrders: string;
	ReadOrderQuery: string;
	ReadOrderRelations: string;
	UpdateBrandOrder: string;
	UpdateOrderItem: string;
	UpdateOrder: string;
	CreatePostLikes: string;
	CreatePost: string;
	ReadPostFilters: string;
	ReadPostLikesFilters: string;
	ReadPostLikesOrders: string;
	ReadPostLikesQuery: string;
	ReadPostLikesRelations: string;
	ReadPostOrders: string;
	ReadPostQuery: string;
	ReadPostRelations: string;
	UpdatePostLikes: string;
	UpdatePost: string;
	CreatePreference: string;
	ReadPreferenceFilters: string;
	ReadPreferenceOrders: string;
	ReadPreferenceQuery: string;
	ReadPreferenceRelations: string;
	UpdatePreference: string;
	CreateProductOptionValue: string;
	CreateProductOption: string;
	CreateProductReview: string;
	CreateProductVariant: string;
	CreateProduct: string;
	CreateTaggedProduct: string;
	ReadProductFilters: string;
	ReadProductOptionFilters: string;
	ReadProductOptionOrders: string;
	ReadProductOptionQuery: string;
	ReadProductOptionRelations: string;
	ReadProductOptionValueFilters: string;
	ReadProductOptionValueOrders: string;
	ReadProductOptionValueQuery: string;
	ReadProductOptionValueRelations: string;
	ReadProductOrders: string;
	ReadProductQuery: string;
	ReadProductRelations: string;
	ReadProductReviewFilters: string;
	ReadProductReviewOrders: string;
	ReadProductReviewQuery: string;
	ReadProductReviewRelations: string;
	ReadProductVariantFilters: string;
	ReadProductVariantOrders: string;
	ReadProductVariantQuery: string;
	ReadProductVariantRelations: string;
	ReadTaggedProductFilters: string;
	ReadTaggedProductOrders: string;
	ReadTaggedProductQuery: string;
	ReadTaggedProductRelations: string;
	UpdateProductOptionValue: string;
	UpdateProductOption: string;
	UpdateProductReview: string;
	UpdateProductVariant: string;
	UpdateProduct: string;
	UpdateTaggedProduct: string;
	CreatePromoCode: string;
	CreatePromotion: string;
	CreateSeasonalPromotion: string;
	ReadPromoCodeFilters: string;
	ReadPromoCodeOrders: string;
	ReadPromoCodeQuery: string;
	ReadPromoCodeRelations: string;
	ReadPromotionFilters: string;
	ReadPromotionOrders: string;
	ReadPromotionQuery: string;
	ReadPromotionRelations: string;
	ReadSeasonalPromotionFilters: string;
	ReadSeasonalPromotionOrders: string;
	ReadSeasonalPromotionQuery: string;
	ReadSeasonalPromotionRelations: string;
	UpdatePromoCode: string;
	UpdatePromotion: string;
	UpdateSeasonalPromotion: string;
	CreateRefund: string;
	ReadRefundFilters: string;
	ReadRefundOrders: string;
	ReadRefundQuery: string;
	ReadRefundRelations: string;
	UpdateRefund: string;
	CreateSavedCollectionItem: string;
	CreateSavedCollection: string;
	ReadSavedCollectionFilters: string;
	ReadSavedCollectionItemFilters: string;
	ReadSavedCollectionItemOrders: string;
	ReadSavedCollectionItemQuery: string;
	ReadSavedCollectionItemRelations: string;
	ReadSavedCollectionOrders: string;
	ReadSavedCollectionQuery: string;
	ReadSavedCollectionRelations: string;
	UpdateSavedCollectionItem: string;
	UpdateSavedCollection: string;
	CreateRecentSearches: string;
	ReadRecentSearchesFilters: string;
	ReadRecentSearchesOrders: string;
	ReadRecentSearchesQuery: string;
	ReadRecentSearchesRelations: string;
	UpdateRecentSearches: string;
	CreateStoryLikes: string;
	CreateStory: string;
	ReadStoryFilters: string;
	ReadStoryLikesFilters: string;
	ReadStoryLikesOrders: string;
	ReadStoryLikesQuery: string;
	ReadStoryLikesRelations: string;
	ReadStoryOrders: string;
	ReadStoryQuery: string;
	ReadStoryRelations: string;
	UpdateStoryLikes: string;
	UpdateStory: string;
	CreateTranslation: string;
	ReadTranslationFilters: string;
	ReadTranslationOrders: string;
	ReadTranslationQuery: string;
	ReadTranslationRelations: string;
	UpdateTranslation: string;
	CreateBrandProfile: string;
	CreateShippingAddress: string;
	CreateShopperProfile: string;
	CreateUser: string;
	ReadBrandProfileFilters: string;
	ReadBrandProfileOrders: string;
	ReadBrandProfileQuery: string;
	ReadBrandProfileRelations: string;
	ReadShippingAddressFilters: string;
	ReadShippingAddressOrders: string;
	ReadShippingAddressQuery: string;
	ReadShippingAddressRelations: string;
	ReadShopperProfileFilters: string;
	ReadShopperProfileOrders: string;
	ReadShopperProfileQuery: string;
	ReadShopperProfileRelations: string;
	ReadUserFilters: string;
	ReadUserOrders: string;
	ReadUserQuery: string;
	ReadUserRelations: string;
	UpdateBrandProfile: string;
	UpdateShippingAddress: string;
	UpdateShopperProfile: string;
	UpdateUser: string;
}

export const SchemaDefs: ISchemaDefs = {
			CreateAffiliationLinkTracking: '#/components/schemas/CreateAffiliationLinkTracking',
	CreateAffiliationLink: '#/components/schemas/CreateAffiliationLink',
	ReadAffiliationLinkFilters: '#/components/schemas/ReadAffiliationLinkFilters',
	ReadAffiliationLinkOrders: '#/components/schemas/ReadAffiliationLinkOrders',
	ReadAffiliationLinkQuery: '#/components/schemas/ReadAffiliationLinkQuery',
	ReadAffiliationLinkRelations: '#/components/schemas/ReadAffiliationLinkRelations',
	ReadAffiliationLinkTrackingFilters: '#/components/schemas/ReadAffiliationLinkTrackingFilters',
	ReadAffiliationLinkTrackingOrders: '#/components/schemas/ReadAffiliationLinkTrackingOrders',
	ReadAffiliationLinkTrackingQuery: '#/components/schemas/ReadAffiliationLinkTrackingQuery',
	ReadAffiliationLinkTrackingRelations: '#/components/schemas/ReadAffiliationLinkTrackingRelations',
	UpdateAffiliationLinkTracking: '#/components/schemas/UpdateAffiliationLinkTracking',
	UpdateAffiliationLink: '#/components/schemas/UpdateAffiliationLink',
	CreateCartItems: '#/components/schemas/CreateCartItems',
	CreateCart: '#/components/schemas/CreateCart',
	ReadCartFilters: '#/components/schemas/ReadCartFilters',
	ReadCartItemsFilters: '#/components/schemas/ReadCartItemsFilters',
	ReadCartItemsOrders: '#/components/schemas/ReadCartItemsOrders',
	ReadCartItemsQuery: '#/components/schemas/ReadCartItemsQuery',
	ReadCartItemsRelations: '#/components/schemas/ReadCartItemsRelations',
	ReadCartOrders: '#/components/schemas/ReadCartOrders',
	ReadCartQuery: '#/components/schemas/ReadCartQuery',
	ReadCartRelations: '#/components/schemas/ReadCartRelations',
	UpdateCartItems: '#/components/schemas/UpdateCartItems',
	UpdateCart: '#/components/schemas/UpdateCart',
	CreateCategory: '#/components/schemas/CreateCategory',
	ReadCategoryFilters: '#/components/schemas/ReadCategoryFilters',
	ReadCategoryOrders: '#/components/schemas/ReadCategoryOrders',
	ReadCategoryQuery: '#/components/schemas/ReadCategoryQuery',
	ReadCategoryRelations: '#/components/schemas/ReadCategoryRelations',
	UpdateCategory: '#/components/schemas/UpdateCategory',
	CreateCollaboration: '#/components/schemas/CreateCollaboration',
	ReadCollaborationFilters: '#/components/schemas/ReadCollaborationFilters',
	ReadCollaborationOrders: '#/components/schemas/ReadCollaborationOrders',
	ReadCollaborationQuery: '#/components/schemas/ReadCollaborationQuery',
	ReadCollaborationRelations: '#/components/schemas/ReadCollaborationRelations',
	UpdateCollaboration: '#/components/schemas/UpdateCollaboration',
	CreateCollection: '#/components/schemas/CreateCollection',
	ReadCollectionFilters: '#/components/schemas/ReadCollectionFilters',
	ReadCollectionOrders: '#/components/schemas/ReadCollectionOrders',
	ReadCollectionQuery: '#/components/schemas/ReadCollectionQuery',
	ReadCollectionRelations: '#/components/schemas/ReadCollectionRelations',
	UpdateCollection: '#/components/schemas/UpdateCollection',
	CreateComment: '#/components/schemas/CreateComment',
	ReadCommentFilters: '#/components/schemas/ReadCommentFilters',
	ReadCommentOrders: '#/components/schemas/ReadCommentOrders',
	ReadCommentQuery: '#/components/schemas/ReadCommentQuery',
	ReadCommentRelations: '#/components/schemas/ReadCommentRelations',
	UpdateComment: '#/components/schemas/UpdateComment',
	CreateConversation: '#/components/schemas/CreateConversation',
	ReadConversationFilters: '#/components/schemas/ReadConversationFilters',
	ReadConversationOrders: '#/components/schemas/ReadConversationOrders',
	ReadConversationQuery: '#/components/schemas/ReadConversationQuery',
	ReadConversationRelations: '#/components/schemas/ReadConversationRelations',
	UpdateConversation: '#/components/schemas/UpdateConversation',
	CreateCountry: '#/components/schemas/CreateCountry',
	ReadCountryFilters: '#/components/schemas/ReadCountryFilters',
	ReadCountryOrders: '#/components/schemas/ReadCountryOrders',
	ReadCountryQuery: '#/components/schemas/ReadCountryQuery',
	ReadCountryRelations: '#/components/schemas/ReadCountryRelations',
	UpdateCountry: '#/components/schemas/UpdateCountry',
	CreateMedia: '#/components/schemas/CreateMedia',
	ReadMediaFilters: '#/components/schemas/ReadMediaFilters',
	ReadMediaOrders: '#/components/schemas/ReadMediaOrders',
	ReadMediaQuery: '#/components/schemas/ReadMediaQuery',
	ReadMediaRelations: '#/components/schemas/ReadMediaRelations',
	UpdateMedia: '#/components/schemas/UpdateMedia',
	CreateMessage: '#/components/schemas/CreateMessage',
	ReadMessageFilters: '#/components/schemas/ReadMessageFilters',
	ReadMessageOrders: '#/components/schemas/ReadMessageOrders',
	ReadMessageQuery: '#/components/schemas/ReadMessageQuery',
	ReadMessageRelations: '#/components/schemas/ReadMessageRelations',
	UpdateMessage: '#/components/schemas/UpdateMessage',
	CreateNotification: '#/components/schemas/CreateNotification',
	ReadNotificationFilters: '#/components/schemas/ReadNotificationFilters',
	ReadNotificationOrders: '#/components/schemas/ReadNotificationOrders',
	ReadNotificationQuery: '#/components/schemas/ReadNotificationQuery',
	ReadNotificationRelations: '#/components/schemas/ReadNotificationRelations',
	UpdateNotification: '#/components/schemas/UpdateNotification',
	CreateBrandOrder: '#/components/schemas/CreateBrandOrder',
	CreateOrderItem: '#/components/schemas/CreateOrderItem',
	CreateOrder: '#/components/schemas/CreateOrder',
	ReadBrandOrderFilters: '#/components/schemas/ReadBrandOrderFilters',
	ReadBrandOrderOrders: '#/components/schemas/ReadBrandOrderOrders',
	ReadBrandOrderQuery: '#/components/schemas/ReadBrandOrderQuery',
	ReadBrandOrderRelations: '#/components/schemas/ReadBrandOrderRelations',
	ReadOrderFilters: '#/components/schemas/ReadOrderFilters',
	ReadOrderItemFilters: '#/components/schemas/ReadOrderItemFilters',
	ReadOrderItemOrders: '#/components/schemas/ReadOrderItemOrders',
	ReadOrderItemQuery: '#/components/schemas/ReadOrderItemQuery',
	ReadOrderItemRelations: '#/components/schemas/ReadOrderItemRelations',
	ReadOrderOrders: '#/components/schemas/ReadOrderOrders',
	ReadOrderQuery: '#/components/schemas/ReadOrderQuery',
	ReadOrderRelations: '#/components/schemas/ReadOrderRelations',
	UpdateBrandOrder: '#/components/schemas/UpdateBrandOrder',
	UpdateOrderItem: '#/components/schemas/UpdateOrderItem',
	UpdateOrder: '#/components/schemas/UpdateOrder',
	CreatePostLikes: '#/components/schemas/CreatePostLikes',
	CreatePost: '#/components/schemas/CreatePost',
	ReadPostFilters: '#/components/schemas/ReadPostFilters',
	ReadPostLikesFilters: '#/components/schemas/ReadPostLikesFilters',
	ReadPostLikesOrders: '#/components/schemas/ReadPostLikesOrders',
	ReadPostLikesQuery: '#/components/schemas/ReadPostLikesQuery',
	ReadPostLikesRelations: '#/components/schemas/ReadPostLikesRelations',
	ReadPostOrders: '#/components/schemas/ReadPostOrders',
	ReadPostQuery: '#/components/schemas/ReadPostQuery',
	ReadPostRelations: '#/components/schemas/ReadPostRelations',
	UpdatePostLikes: '#/components/schemas/UpdatePostLikes',
	UpdatePost: '#/components/schemas/UpdatePost',
	CreatePreference: '#/components/schemas/CreatePreference',
	ReadPreferenceFilters: '#/components/schemas/ReadPreferenceFilters',
	ReadPreferenceOrders: '#/components/schemas/ReadPreferenceOrders',
	ReadPreferenceQuery: '#/components/schemas/ReadPreferenceQuery',
	ReadPreferenceRelations: '#/components/schemas/ReadPreferenceRelations',
	UpdatePreference: '#/components/schemas/UpdatePreference',
	CreateProductOptionValue: '#/components/schemas/CreateProductOptionValue',
	CreateProductOption: '#/components/schemas/CreateProductOption',
	CreateProductReview: '#/components/schemas/CreateProductReview',
	CreateProductVariant: '#/components/schemas/CreateProductVariant',
	CreateProduct: '#/components/schemas/CreateProduct',
	CreateTaggedProduct: '#/components/schemas/CreateTaggedProduct',
	ReadProductFilters: '#/components/schemas/ReadProductFilters',
	ReadProductOptionFilters: '#/components/schemas/ReadProductOptionFilters',
	ReadProductOptionOrders: '#/components/schemas/ReadProductOptionOrders',
	ReadProductOptionQuery: '#/components/schemas/ReadProductOptionQuery',
	ReadProductOptionRelations: '#/components/schemas/ReadProductOptionRelations',
	ReadProductOptionValueFilters: '#/components/schemas/ReadProductOptionValueFilters',
	ReadProductOptionValueOrders: '#/components/schemas/ReadProductOptionValueOrders',
	ReadProductOptionValueQuery: '#/components/schemas/ReadProductOptionValueQuery',
	ReadProductOptionValueRelations: '#/components/schemas/ReadProductOptionValueRelations',
	ReadProductOrders: '#/components/schemas/ReadProductOrders',
	ReadProductQuery: '#/components/schemas/ReadProductQuery',
	ReadProductRelations: '#/components/schemas/ReadProductRelations',
	ReadProductReviewFilters: '#/components/schemas/ReadProductReviewFilters',
	ReadProductReviewOrders: '#/components/schemas/ReadProductReviewOrders',
	ReadProductReviewQuery: '#/components/schemas/ReadProductReviewQuery',
	ReadProductReviewRelations: '#/components/schemas/ReadProductReviewRelations',
	ReadProductVariantFilters: '#/components/schemas/ReadProductVariantFilters',
	ReadProductVariantOrders: '#/components/schemas/ReadProductVariantOrders',
	ReadProductVariantQuery: '#/components/schemas/ReadProductVariantQuery',
	ReadProductVariantRelations: '#/components/schemas/ReadProductVariantRelations',
	ReadTaggedProductFilters: '#/components/schemas/ReadTaggedProductFilters',
	ReadTaggedProductOrders: '#/components/schemas/ReadTaggedProductOrders',
	ReadTaggedProductQuery: '#/components/schemas/ReadTaggedProductQuery',
	ReadTaggedProductRelations: '#/components/schemas/ReadTaggedProductRelations',
	UpdateProductOptionValue: '#/components/schemas/UpdateProductOptionValue',
	UpdateProductOption: '#/components/schemas/UpdateProductOption',
	UpdateProductReview: '#/components/schemas/UpdateProductReview',
	UpdateProductVariant: '#/components/schemas/UpdateProductVariant',
	UpdateProduct: '#/components/schemas/UpdateProduct',
	UpdateTaggedProduct: '#/components/schemas/UpdateTaggedProduct',
	CreatePromoCode: '#/components/schemas/CreatePromoCode',
	CreatePromotion: '#/components/schemas/CreatePromotion',
	CreateSeasonalPromotion: '#/components/schemas/CreateSeasonalPromotion',
	ReadPromoCodeFilters: '#/components/schemas/ReadPromoCodeFilters',
	ReadPromoCodeOrders: '#/components/schemas/ReadPromoCodeOrders',
	ReadPromoCodeQuery: '#/components/schemas/ReadPromoCodeQuery',
	ReadPromoCodeRelations: '#/components/schemas/ReadPromoCodeRelations',
	ReadPromotionFilters: '#/components/schemas/ReadPromotionFilters',
	ReadPromotionOrders: '#/components/schemas/ReadPromotionOrders',
	ReadPromotionQuery: '#/components/schemas/ReadPromotionQuery',
	ReadPromotionRelations: '#/components/schemas/ReadPromotionRelations',
	ReadSeasonalPromotionFilters: '#/components/schemas/ReadSeasonalPromotionFilters',
	ReadSeasonalPromotionOrders: '#/components/schemas/ReadSeasonalPromotionOrders',
	ReadSeasonalPromotionQuery: '#/components/schemas/ReadSeasonalPromotionQuery',
	ReadSeasonalPromotionRelations: '#/components/schemas/ReadSeasonalPromotionRelations',
	UpdatePromoCode: '#/components/schemas/UpdatePromoCode',
	UpdatePromotion: '#/components/schemas/UpdatePromotion',
	UpdateSeasonalPromotion: '#/components/schemas/UpdateSeasonalPromotion',
	CreateRefund: '#/components/schemas/CreateRefund',
	ReadRefundFilters: '#/components/schemas/ReadRefundFilters',
	ReadRefundOrders: '#/components/schemas/ReadRefundOrders',
	ReadRefundQuery: '#/components/schemas/ReadRefundQuery',
	ReadRefundRelations: '#/components/schemas/ReadRefundRelations',
	UpdateRefund: '#/components/schemas/UpdateRefund',
	CreateSavedCollectionItem: '#/components/schemas/CreateSavedCollectionItem',
	CreateSavedCollection: '#/components/schemas/CreateSavedCollection',
	ReadSavedCollectionFilters: '#/components/schemas/ReadSavedCollectionFilters',
	ReadSavedCollectionItemFilters: '#/components/schemas/ReadSavedCollectionItemFilters',
	ReadSavedCollectionItemOrders: '#/components/schemas/ReadSavedCollectionItemOrders',
	ReadSavedCollectionItemQuery: '#/components/schemas/ReadSavedCollectionItemQuery',
	ReadSavedCollectionItemRelations: '#/components/schemas/ReadSavedCollectionItemRelations',
	ReadSavedCollectionOrders: '#/components/schemas/ReadSavedCollectionOrders',
	ReadSavedCollectionQuery: '#/components/schemas/ReadSavedCollectionQuery',
	ReadSavedCollectionRelations: '#/components/schemas/ReadSavedCollectionRelations',
	UpdateSavedCollectionItem: '#/components/schemas/UpdateSavedCollectionItem',
	UpdateSavedCollection: '#/components/schemas/UpdateSavedCollection',
	CreateRecentSearches: '#/components/schemas/CreateRecentSearches',
	ReadRecentSearchesFilters: '#/components/schemas/ReadRecentSearchesFilters',
	ReadRecentSearchesOrders: '#/components/schemas/ReadRecentSearchesOrders',
	ReadRecentSearchesQuery: '#/components/schemas/ReadRecentSearchesQuery',
	ReadRecentSearchesRelations: '#/components/schemas/ReadRecentSearchesRelations',
	UpdateRecentSearches: '#/components/schemas/UpdateRecentSearches',
	CreateStoryLikes: '#/components/schemas/CreateStoryLikes',
	CreateStory: '#/components/schemas/CreateStory',
	ReadStoryFilters: '#/components/schemas/ReadStoryFilters',
	ReadStoryLikesFilters: '#/components/schemas/ReadStoryLikesFilters',
	ReadStoryLikesOrders: '#/components/schemas/ReadStoryLikesOrders',
	ReadStoryLikesQuery: '#/components/schemas/ReadStoryLikesQuery',
	ReadStoryLikesRelations: '#/components/schemas/ReadStoryLikesRelations',
	ReadStoryOrders: '#/components/schemas/ReadStoryOrders',
	ReadStoryQuery: '#/components/schemas/ReadStoryQuery',
	ReadStoryRelations: '#/components/schemas/ReadStoryRelations',
	UpdateStoryLikes: '#/components/schemas/UpdateStoryLikes',
	UpdateStory: '#/components/schemas/UpdateStory',
	CreateTranslation: '#/components/schemas/CreateTranslation',
	ReadTranslationFilters: '#/components/schemas/ReadTranslationFilters',
	ReadTranslationOrders: '#/components/schemas/ReadTranslationOrders',
	ReadTranslationQuery: '#/components/schemas/ReadTranslationQuery',
	ReadTranslationRelations: '#/components/schemas/ReadTranslationRelations',
	UpdateTranslation: '#/components/schemas/UpdateTranslation',
	CreateBrandProfile: '#/components/schemas/CreateBrandProfile',
	CreateShippingAddress: '#/components/schemas/CreateShippingAddress',
	CreateShopperProfile: '#/components/schemas/CreateShopperProfile',
	CreateUser: '#/components/schemas/CreateUser',
	ReadBrandProfileFilters: '#/components/schemas/ReadBrandProfileFilters',
	ReadBrandProfileOrders: '#/components/schemas/ReadBrandProfileOrders',
	ReadBrandProfileQuery: '#/components/schemas/ReadBrandProfileQuery',
	ReadBrandProfileRelations: '#/components/schemas/ReadBrandProfileRelations',
	ReadShippingAddressFilters: '#/components/schemas/ReadShippingAddressFilters',
	ReadShippingAddressOrders: '#/components/schemas/ReadShippingAddressOrders',
	ReadShippingAddressQuery: '#/components/schemas/ReadShippingAddressQuery',
	ReadShippingAddressRelations: '#/components/schemas/ReadShippingAddressRelations',
	ReadShopperProfileFilters: '#/components/schemas/ReadShopperProfileFilters',
	ReadShopperProfileOrders: '#/components/schemas/ReadShopperProfileOrders',
	ReadShopperProfileQuery: '#/components/schemas/ReadShopperProfileQuery',
	ReadShopperProfileRelations: '#/components/schemas/ReadShopperProfileRelations',
	ReadUserFilters: '#/components/schemas/ReadUserFilters',
	ReadUserOrders: '#/components/schemas/ReadUserOrders',
	ReadUserQuery: '#/components/schemas/ReadUserQuery',
	ReadUserRelations: '#/components/schemas/ReadUserRelations',
	UpdateBrandProfile: '#/components/schemas/UpdateBrandProfile',
	UpdateShippingAddress: '#/components/schemas/UpdateShippingAddress',
	UpdateShopperProfile: '#/components/schemas/UpdateShopperProfile',
	UpdateUser: '#/components/schemas/UpdateUser',
}