
interface ISchemaDefs {
  [key: string]: string;
		CreateAd: string;
	ReadAdFilters: string;
	ReadAdOrders: string;
	ReadAdQuery: string;
	ReadAdRelations: string;
	UpdateAd: string;
	CreateBanner: string;
	ReadBannerFilters: string;
	ReadBannerOrders: string;
	ReadBannerQuery: string;
	ReadBannerRelations: string;
	UpdateBanner: string;
	CreateCategory: string;
	ReadCategoryFilters: string;
	ReadCategoryOrders: string;
	ReadCategoryQuery: string;
	ReadCategoryRelations: string;
	UpdateCategory: string;
	CreateCategoryFilter: string;
	ReadCategoryFilterFilters: string;
	ReadCategoryFilterOrders: string;
	ReadCategoryFilterQuery: string;
	ReadCategoryFilterRelations: string;
	UpdateCategoryFilter: string;
	CreateConversation: string;
	ReadConversationFilters: string;
	ReadConversationOrders: string;
	ReadConversationQuery: string;
	ReadConversationRelations: string;
	UpdateConversation: string;
	CreateCountry: string;
	ReadCountryFilters: string;
	ReadCountryOrders: string;
	ReadCountryQuery: string;
	ReadCountryRelations: string;
	UpdateCountry: string;
	CreateFavorite: string;
	ReadFavoriteFilters: string;
	ReadFavoriteOrders: string;
	ReadFavoriteQuery: string;
	ReadFavoriteRelations: string;
	UpdateFavorite: string;
	CreateFeedback: string;
	ReadFeedbackFilters: string;
	ReadFeedbackOrders: string;
	ReadFeedbackQuery: string;
	ReadFeedbackRelations: string;
	UpdateFeedback: string;
	CreateGovernorate: string;
	ReadGovernorateFilters: string;
	ReadGovernorateOrders: string;
	ReadGovernorateQuery: string;
	ReadGovernorateRelations: string;
	UpdateGovernorate: string;
	CreateMedia: string;
	ReadMediaFilters: string;
	ReadMediaOrders: string;
	ReadMediaQuery: string;
	ReadMediaRelations: string;
	UpdateMedia: string;
	CreateMessage: string;
	ReadMessageFilters: string;
	ReadMessageOrders: string;
	ReadMessageQuery: string;
	ReadMessageRelations: string;
	UpdateMessage: string;
	CreateNotification: string;
	ReadNotificationFilters: string;
	ReadNotificationOrders: string;
	ReadNotificationQuery: string;
	ReadNotificationRelations: string;
	UpdateNotification: string;
	CreatePlan: string;
	ReadPlanFilters: string;
	ReadPlanOrders: string;
	ReadPlanQuery: string;
	ReadPlanRelations: string;
	UpdatePlan: string;
	CreateRating: string;
	ReadRatingFilters: string;
	ReadRatingOrders: string;
	ReadRatingQuery: string;
	ReadRatingRelations: string;
	UpdateRating: string;
	CreateRedeem: string;
	ReadRedeemFilters: string;
	ReadRedeemOrders: string;
	ReadRedeemQuery: string;
	ReadRedeemRelations: string;
	UpdateRedeem: string;
	CreateStatic: string;
	ReadStaticFilters: string;
	ReadStaticOrders: string;
	ReadStaticQuery: string;
	ReadStaticRelations: string;
	UpdateStatic: string;
	CreateTranslation: string;
	ReadTranslationFilters: string;
	ReadTranslationOrders: string;
	ReadTranslationQuery: string;
	ReadTranslationRelations: string;
	UpdateTranslation: string;
	CreateUserInterest: string;
	CreateUser: string;
	ReadUserFilters: string;
	ReadUserInterestFilters: string;
	ReadUserInterestOrders: string;
	ReadUserInterestQuery: string;
	ReadUserInterestRelations: string;
	ReadUserOrders: string;
	ReadUserQuery: string;
	ReadUserRelations: string;
	UpdateUserInterest: string;
	UpdateUser: string;
	CreateWalletLog: string;
	CreateWallet: string;
	ReadWalletFilters: string;
	ReadWalletLogFilters: string;
	ReadWalletLogOrders: string;
	ReadWalletLogQuery: string;
	ReadWalletLogRelations: string;
	ReadWalletOrders: string;
	ReadWalletQuery: string;
	ReadWalletRelations: string;
	UpdateWalletLog: string;
	UpdateWallet: string;
}

export const SchemaDefs: ISchemaDefs = {
			CreateAd: '#/components/schemas/CreateAd',
	ReadAdFilters: '#/components/schemas/ReadAdFilters',
	ReadAdOrders: '#/components/schemas/ReadAdOrders',
	ReadAdQuery: '#/components/schemas/ReadAdQuery',
	ReadAdRelations: '#/components/schemas/ReadAdRelations',
	UpdateAd: '#/components/schemas/UpdateAd',
	CreateBanner: '#/components/schemas/CreateBanner',
	ReadBannerFilters: '#/components/schemas/ReadBannerFilters',
	ReadBannerOrders: '#/components/schemas/ReadBannerOrders',
	ReadBannerQuery: '#/components/schemas/ReadBannerQuery',
	ReadBannerRelations: '#/components/schemas/ReadBannerRelations',
	UpdateBanner: '#/components/schemas/UpdateBanner',
	CreateCategory: '#/components/schemas/CreateCategory',
	ReadCategoryFilters: '#/components/schemas/ReadCategoryFilters',
	ReadCategoryOrders: '#/components/schemas/ReadCategoryOrders',
	ReadCategoryQuery: '#/components/schemas/ReadCategoryQuery',
	ReadCategoryRelations: '#/components/schemas/ReadCategoryRelations',
	UpdateCategory: '#/components/schemas/UpdateCategory',
	CreateCategoryFilter: '#/components/schemas/CreateCategoryFilter',
	ReadCategoryFilterFilters: '#/components/schemas/ReadCategoryFilterFilters',
	ReadCategoryFilterOrders: '#/components/schemas/ReadCategoryFilterOrders',
	ReadCategoryFilterQuery: '#/components/schemas/ReadCategoryFilterQuery',
	ReadCategoryFilterRelations: '#/components/schemas/ReadCategoryFilterRelations',
	UpdateCategoryFilter: '#/components/schemas/UpdateCategoryFilter',
	CreateConversation: '#/components/schemas/CreateConversation',
	ReadConversationFilters: '#/components/schemas/ReadConversationFilters',
	ReadConversationOrders: '#/components/schemas/ReadConversationOrders',
	ReadConversationQuery: '#/components/schemas/ReadConversationQuery',
	ReadConversationRelations: '#/components/schemas/ReadConversationRelations',
	UpdateConversation: '#/components/schemas/UpdateConversation',
	CreateCountry: '#/components/schemas/CreateCountry',
	ReadCountryFilters: '#/components/schemas/ReadCountryFilters',
	ReadCountryOrders: '#/components/schemas/ReadCountryOrders',
	ReadCountryQuery: '#/components/schemas/ReadCountryQuery',
	ReadCountryRelations: '#/components/schemas/ReadCountryRelations',
	UpdateCountry: '#/components/schemas/UpdateCountry',
	CreateFavorite: '#/components/schemas/CreateFavorite',
	ReadFavoriteFilters: '#/components/schemas/ReadFavoriteFilters',
	ReadFavoriteOrders: '#/components/schemas/ReadFavoriteOrders',
	ReadFavoriteQuery: '#/components/schemas/ReadFavoriteQuery',
	ReadFavoriteRelations: '#/components/schemas/ReadFavoriteRelations',
	UpdateFavorite: '#/components/schemas/UpdateFavorite',
	CreateFeedback: '#/components/schemas/CreateFeedback',
	ReadFeedbackFilters: '#/components/schemas/ReadFeedbackFilters',
	ReadFeedbackOrders: '#/components/schemas/ReadFeedbackOrders',
	ReadFeedbackQuery: '#/components/schemas/ReadFeedbackQuery',
	ReadFeedbackRelations: '#/components/schemas/ReadFeedbackRelations',
	UpdateFeedback: '#/components/schemas/UpdateFeedback',
	CreateGovernorate: '#/components/schemas/CreateGovernorate',
	ReadGovernorateFilters: '#/components/schemas/ReadGovernorateFilters',
	ReadGovernorateOrders: '#/components/schemas/ReadGovernorateOrders',
	ReadGovernorateQuery: '#/components/schemas/ReadGovernorateQuery',
	ReadGovernorateRelations: '#/components/schemas/ReadGovernorateRelations',
	UpdateGovernorate: '#/components/schemas/UpdateGovernorate',
	CreateMedia: '#/components/schemas/CreateMedia',
	ReadMediaFilters: '#/components/schemas/ReadMediaFilters',
	ReadMediaOrders: '#/components/schemas/ReadMediaOrders',
	ReadMediaQuery: '#/components/schemas/ReadMediaQuery',
	ReadMediaRelations: '#/components/schemas/ReadMediaRelations',
	UpdateMedia: '#/components/schemas/UpdateMedia',
	CreateMessage: '#/components/schemas/CreateMessage',
	ReadMessageFilters: '#/components/schemas/ReadMessageFilters',
	ReadMessageOrders: '#/components/schemas/ReadMessageOrders',
	ReadMessageQuery: '#/components/schemas/ReadMessageQuery',
	ReadMessageRelations: '#/components/schemas/ReadMessageRelations',
	UpdateMessage: '#/components/schemas/UpdateMessage',
	CreateNotification: '#/components/schemas/CreateNotification',
	ReadNotificationFilters: '#/components/schemas/ReadNotificationFilters',
	ReadNotificationOrders: '#/components/schemas/ReadNotificationOrders',
	ReadNotificationQuery: '#/components/schemas/ReadNotificationQuery',
	ReadNotificationRelations: '#/components/schemas/ReadNotificationRelations',
	UpdateNotification: '#/components/schemas/UpdateNotification',
	CreatePlan: '#/components/schemas/CreatePlan',
	ReadPlanFilters: '#/components/schemas/ReadPlanFilters',
	ReadPlanOrders: '#/components/schemas/ReadPlanOrders',
	ReadPlanQuery: '#/components/schemas/ReadPlanQuery',
	ReadPlanRelations: '#/components/schemas/ReadPlanRelations',
	UpdatePlan: '#/components/schemas/UpdatePlan',
	CreateRating: '#/components/schemas/CreateRating',
	ReadRatingFilters: '#/components/schemas/ReadRatingFilters',
	ReadRatingOrders: '#/components/schemas/ReadRatingOrders',
	ReadRatingQuery: '#/components/schemas/ReadRatingQuery',
	ReadRatingRelations: '#/components/schemas/ReadRatingRelations',
	UpdateRating: '#/components/schemas/UpdateRating',
	CreateRedeem: '#/components/schemas/CreateRedeem',
	ReadRedeemFilters: '#/components/schemas/ReadRedeemFilters',
	ReadRedeemOrders: '#/components/schemas/ReadRedeemOrders',
	ReadRedeemQuery: '#/components/schemas/ReadRedeemQuery',
	ReadRedeemRelations: '#/components/schemas/ReadRedeemRelations',
	UpdateRedeem: '#/components/schemas/UpdateRedeem',
	CreateStatic: '#/components/schemas/CreateStatic',
	ReadStaticFilters: '#/components/schemas/ReadStaticFilters',
	ReadStaticOrders: '#/components/schemas/ReadStaticOrders',
	ReadStaticQuery: '#/components/schemas/ReadStaticQuery',
	ReadStaticRelations: '#/components/schemas/ReadStaticRelations',
	UpdateStatic: '#/components/schemas/UpdateStatic',
	CreateTranslation: '#/components/schemas/CreateTranslation',
	ReadTranslationFilters: '#/components/schemas/ReadTranslationFilters',
	ReadTranslationOrders: '#/components/schemas/ReadTranslationOrders',
	ReadTranslationQuery: '#/components/schemas/ReadTranslationQuery',
	ReadTranslationRelations: '#/components/schemas/ReadTranslationRelations',
	UpdateTranslation: '#/components/schemas/UpdateTranslation',
	CreateUserInterest: '#/components/schemas/CreateUserInterest',
	CreateUser: '#/components/schemas/CreateUser',
	ReadUserFilters: '#/components/schemas/ReadUserFilters',
	ReadUserInterestFilters: '#/components/schemas/ReadUserInterestFilters',
	ReadUserInterestOrders: '#/components/schemas/ReadUserInterestOrders',
	ReadUserInterestQuery: '#/components/schemas/ReadUserInterestQuery',
	ReadUserInterestRelations: '#/components/schemas/ReadUserInterestRelations',
	ReadUserOrders: '#/components/schemas/ReadUserOrders',
	ReadUserQuery: '#/components/schemas/ReadUserQuery',
	ReadUserRelations: '#/components/schemas/ReadUserRelations',
	UpdateUserInterest: '#/components/schemas/UpdateUserInterest',
	UpdateUser: '#/components/schemas/UpdateUser',
	CreateWalletLog: '#/components/schemas/CreateWalletLog',
	CreateWallet: '#/components/schemas/CreateWallet',
	ReadWalletFilters: '#/components/schemas/ReadWalletFilters',
	ReadWalletLogFilters: '#/components/schemas/ReadWalletLogFilters',
	ReadWalletLogOrders: '#/components/schemas/ReadWalletLogOrders',
	ReadWalletLogQuery: '#/components/schemas/ReadWalletLogQuery',
	ReadWalletLogRelations: '#/components/schemas/ReadWalletLogRelations',
	ReadWalletOrders: '#/components/schemas/ReadWalletOrders',
	ReadWalletQuery: '#/components/schemas/ReadWalletQuery',
	ReadWalletRelations: '#/components/schemas/ReadWalletRelations',
	UpdateWalletLog: '#/components/schemas/UpdateWalletLog',
	UpdateWallet: '#/components/schemas/UpdateWallet',
}