services:
  postgres-db:
    container_name: nestjs-project-postgres-db
    image: postgres:16
    restart: unless-stopped
    env_file: '.env'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - nestjs-project-db-vol:/var/lib/postgresql/data
    networks:
      - nestjs-project-net

  api:
    container_name: nestjs-project-api
    depends_on:
      - postgres-db
    build: .
    restart: unless-stopped
    env_file: '.env'
    ports:
      - 3000:$PORT
    volumes:
      - ./:/app
    networks:
      - nestjs-project-net

networks:
  nestjs-project-net:
volumes:
  nestjs-project-db-vol:
