import * as v from 'valibot';

export const CreateTaggedProductSchema = v.pipe(v.object({product: v.nullish(v.union([v.number(), v.object({isArchived: v.boolean(),
title: v.nullish(v.string()),
description: v.nullish(v.string()),
basePrice: v.nullish(v.number()),
sku: v.nullish(v.string()),
currency: v.nullish(v.string()),
stock: v.number(),
lastStockUpdate: v.nullish(v.pipe(v.string('Invalid type: Expected ISO timestamp string'), v.isoTimestamp())),
isOutOfStock: v.boolean(),
isFeatured: v.boolean(),
deliveryEstimationInDays: v.number(),
brandId: v.nullish(v.number()),
categoryId: v.nullish(v.number()),
subCategoryId: v.nullish(v.number()),
averageRating: v.number(),
isSaved: v.boolean()})])),
post: v.nullish(v.union([v.number(), v.object({caption: v.nullish(v.string()),
postedById: v.number(),
thumbnailId: v.nullish(v.number()),
likesCount: v.number(),
commentsCount: v.number(),
taggedProductsCount: v.number(),
taggedUsersCount: v.number(),
isLiked: v.undefinedable(v.boolean())})])),
story: v.nullish(v.union([v.number(), v.object({background: v.nullish(v.string()),
text: v.nullish(v.string()),
postedById: v.number(),
taggedProductsCount: v.number(),
taggedUsersCount: v.number(),
isLiked: v.undefinedable(v.boolean()),
isViewed: v.undefinedable(v.boolean())})])),
affiliationLink: v.nullish(v.union([v.number(), v.object({isDisabled: v.boolean(),
url: v.string(),
productId: v.number(),
shopperId: v.number()})])),
productId: v.nullish(v.number()),
postId: v.nullish(v.number()),
storyId: v.nullish(v.number()),
affiliationLinkId: v.nullish(v.number())}),v.metadata({product: 'ProductEntity',
post: 'PostEntity',
story: 'StoryEntity',
affiliationLink: 'AffiliationLinkEntity'}))

export type TCreateTaggedProductSchema = v.InferInput<typeof CreateTaggedProductSchema>
